# -*- coding: utf-8 -*-

# Tickers on Oslo Børs
ose = [("ASC", "ABG Sundal Collier Holding"),
       ("AFG", "AF Gruppen"),
       ("AKA", "Akastor"),
       ("AKER", "Aker"),
       ("AKERBP", "Aker BP"),
       ("AKSO", "Aker Solutions"),
       ("AKVA", "AKVA Group"),
       ("AMSC", "American Shipping Company"),
       ("APP", "Apptix"),
       ("AQUA", "Aqualis"),
       ("ARCHER", "Archer"),
       ("ARCUS", "Arcus"),
       ("AFK", "Arendals Fossekompani 2"),
       ("ASETEK", "Asetek"),
       ("ATEA", "Atea"),
       ("ATLA", "NOK Atlantic Petroleum"),
       ("AURG", "Aurskog Sparebank"),
       ("AUSS", "Austevoll Seafood"),
       ("AVANCE", "Avance Gas Holding"),
       ("AVM", "Avocet Mining"),
       ("AXA", "Axactor"),
       ("B2H", "B2Holding"),
       ("BAKKA", "Bakkafrost"),
       ("BEL", "Belships"),
       ("BERGEN", "Bergen Group"),
       ("BGBIO", "BerGenBio"),
       ("BIOTEC", "Biotec Pharmacon"),
       ("BON", "Bonheur"),
       ("BOR", "Borgestad"),
       ("BRG", "Borregaard"),
       ("BOUVET", "Bouvet"),
       ("BWLPG", "BW LPG"),
       ("BWO", "BW Offshore Limited"),
       ("BMA", "Byggma"),
       ("COV", "ContextVision"),
       ("CXENSE", "Cxense"),
       ("DAT", "Data Respons"),
       ("DESSC", "Deep Sea Supply"),
       ("DNB", "DNB"),
       ("DNO", "DNO"),
       ("DOF", "DOF"),
       ("EIOF", "Eidesvik Offshore"),
       ("EKO", "Ekornes"),
       ("EMGS", "Electromagnetic Geoservices"),
       ("EMAS", "EMAS Offshore"),
       ("ENTRA", "Entra"),
       ("EPR", "Europris"),
       ("FAR", "Farstad Shipping"),
       ("FOE", "Fred. Olsen Energy"),
       ("FRO", "Frontline"),
       ("FUNCOM", "Funcom"),
       ("GIG", "Gaming Innovation Group"),
       ("RISH", "GC Rieber Shipping"),
       ("GJF", "Gjensidige Forsikring"),
       ("GOGL", "Golden Ocean Group"),
       ("GOD", "Goodtech"),
       ("GSF", "Grieg Seafood"),
       ("GYL", "Gyldendal"),
       ("HNA", "Hafslund ser. A"),
       ("HNB", "Hafslund ser. B"),
       ("HAVI", "Havila Shipping"),
       ("HYARD", "Havyard Group"),
       ("HELG", "Helgeland Sparebank"),
       ("HEX", "Hexagon Composites"),
       ("HIDDN", "Hiddn Solutions"),
       ("HLNG", "Höegh LNG Holdings"),
       ("HSPG", "Høland og Setskog Sparebank"),
       ("IMSK", "I.M. Skaugen"),
       ("IDEX", "IDEX"),
       ("INC", "Incus Investor"),
       ("ISSG", "Indre Sogn Sparebank"),
       ("INSR", "Insr Insurance Group"),
       ("IOX", "InterOil Exploration and Production"),
       ("ITX", "Intex Resources"),
       ("ITE", "Itera"),
       ("JIN", "Jinhui Shipping and Transportation"),
       ("JAEREN", "Jæren Sparebank"),
       ("KID", "Kid"),
       ("KIT", "Kitron"),
       ("KOA", "Kongsberg Automotive"),
       ("KOG", "Kongsberg Gruppen"),
       ("KVAER", "Kværner"),
       ("LSG", "Lerøy Seafood Group"),
       ("LINK", "Link Mobility Group"),
       ("MHG", "Marine Harvest"),
       ("MEDI", "Medistim"),
       ("MELG", "Melhus Sparebank"),
       ("MULTI", "Multiconsult"),
       ("NAPA", "Napatech"),
       ("NAVA", "Navamedic"),
       ("NEL", "NEL"),
       ("NEXT", "NEXT Biometrics Group"),
       ("NGT", "NextGenTel Holding"),
       ("NANO", "Nordic Nanovector"),
       ("NOD", "Nordic Semiconductor"),
       ("NHY", "Norsk Hydro"),
       ("NSG", "Norske Skogindustrier"),
       ("NRS", "Norway Royal Salmon"),
       ("NAS", "Norwegian Air Shuttle"),
       ("NOR", "Norwegian Energy Company"),
       ("NOFI", "Norwegian Finans Holding"),
       ("NPRO", "Norwegian Property"),
       ("NRC", "NRC Group"),
       ("NTS", "NTS"),
       ("OCY", "Ocean Yield"),
       ("OTS", "Oceanteam"),
       ("ODL", "Odfjell Drilling"),
       ("ODF", "Odfjell ser. A"),
       ("ODFB", "Odfjell ser. B"),
       ("OLT", "Olav Thon Eiendomsselskap"),
       ("OPERA", "Opera Software"),
       ("ORK", "Orkla"),
       ("PEN", "Panoro Energy"),
       ("PARB", "Pareto Bank"),
       ("PGS", "Petroleum Geo-Services"),
       ("PDR", "Petrolia"),
       ("PHO", "Photocure"),
       ("PLCS", "Polarcus"),
       ("POL", "Polaris Media"),
       ("PRS", "Prosafe"),
       ("PROTCT", "Protector Forsikring"),
       ("QFR", "Q-Free"),
       ("QEC", "Questerre Energy Corporation"),
       ("RAKP", "RAK Petroleum"),
       ("REACH", "Reach Subsea"),
       ("REC", "REC Silicon"),
       ("RENO", "RenoNorden"),
       ("SALM", "SalMar"),
       ("SADG", "Sandnes Sparebank"),
       ("SAS", "NOK SAS AB"),
       ("SSO", "Scatec Solar"),
       ("SCHA", "Schibsted ser. A"),
       ("SCHB", "Schibsted ser. B"),
       ("SBX", "SeaBird Exploration"),
       ("SDRL", "Seadrill"),
       ("SBO", "Selvaag Bolig"),
       ("SEVDR", "Sevan Drilling"),
       ("SEVAN", "Sevan Marine"),
       ("SIOFF", "Siem Offshore"),
       ("SKBN", "Skandiabanken"),
       ("SKI", "Skiens Aktiemølle"),
       ("SKUE", "Skue Sparebank"),
       ("SOLON", "Solon Eiendom"),
       ("SOFF", "Solstad Offshore ser. A"),
       ("SOFFB", "Solstad Offshore ser. B"),
       ("SOLV", "Solvang"),
       ("SONG", "Songa Offshore"),
       ("SBVG", "SpareBank 1 BV"),
       ("NONG", "SpareBank 1 Nord-Norge"),
       ("RING", "SpareBank 1 Ringerike Hadeland"),
       ("MING", "SpareBank 1 SMN"),
       ("SRBANK", "SpareBank 1 SR-Bank"),
       ("SOAG", "SpareBank 1 Østfold Akershus"),
       ("MORG", "Sparebanken Møre"),
       ("SOR", "Sparebanken Sør"),
       ("SVEG", "Sparebanken Vest"),
       ("SPOG", "Sparebanken Øst"),
       ("SPU", "Spectrum"),
       ("STL", "Statoil"),
       ("SNI", "Stolt-Nielsen"),
       ("STB", "Storebrand"),
       ("STORM", "Storm Real Estate"),
       ("STRONG", "StrongPoint"),
       ("SUBC", "Subsea 7"),
       ("TIL", "Tanker Investments"),
       ("TRVX", "Targovax"),
       ("TEAM", "Team Tankers International"),
       ("TECH", "Techstep"),
       ("TEL", "Telenor"),
       ("TGS", "TGS-NOPEC Geophysical Company"),
       ("SSC", "The Scottish Salmon Company"),
       ("THIN", "Thin Film Electronics"),
       ("TOM", "Tomra Systems"),
       ("TOTG", "Totens Sparebank"),
       ("TRE", "Treasure"),
       ("TTS", "TTS Group"),
       ("VEI", "Veidekke"),
       ("VVL", "Voss Veksel- og Landmandsbank"),
       ("WWL", "Wallenius Wilhelmsen Logistics"),
       ("WEIFA", "Weifa"),
       ("WRL", "Wentworth Resources"),
       ("WWI", "Wilh. Wilhelmsen Holding ser. A"),
       ("WWIB", "Wilh. Wilhelmsen Holding ser. B"),
       ("WILS", "Wilson"),
       ("XXL", "XXL"),
       ("YAR", "Yara International"),
       ("ZAL", "Zalaris"),]

# Tickers on Oslo Axess
oax = [("AEGA", "Aega"),
       ("APCL", "African Petroleum Corporation"),
       ("ABT", "Aqua Bio Technology"),
       ("AWDR", "Awilco Drilling"),
       ("ALNG", "Awilco LNG"),
       ("BXPL", "Badger Explorer"),
       ("EAM", "EAM Solar"),
       ("FLNG", "FLEX LNG"),
       ("HBC", "Hofseth BioCare"),
       ("HUGO", "Hugo Games"),
       ("MSEIS", "Magseis"),
       ("MCG", "MultiClient Geophysical"),
       ("NATTO", "NattoPharma"),
       ("NOM", "Nordic Mining"),
       ("NORTH", "North Energy"),
       ("PCIB", "PCI Biotech Holding"),
       ("PHLY", "Philly Shipyard"),
       ("PPG", "PREF Pioneer Property Group"),
       ("ROM", "RomReal"),
       ("SDSD", "S.D. Standard Drilling"),
       ("SAGA", "Saga Tankers"),
       ("SSHIP", "Scanship Holding"),
       ("UMS", "Unified Messaging Systems"),
       ("VISTIN", "Vistin Pharma"),]

merk = [("AASB-ME", "Aasen Sparebank"),
        ("ATLU-ME", "Atlantic Lumpus"),
        ("BSP-ME", "Black Sea Property"),
        ("EPIC-ME", "Epic Gas"),
        ("GENT-ME", "Gentian Diagnostics"),
        ("INDUCT-ME", "Induct"),
        ("KOLKAP-ME", "Kolibri Kapital"),
        ("MONO-ME", "Monobank"),
        ("OXXY-ME", "Oxxy Group"),
        ("SIAF-ME", "Sino Agro Food"),
        ("SBULK-ME", "Songa Bulk"),
        ("WRE-ME", "WR Entertainment"),]

markets = {'OSE':  {'tickers': ose, 'long_name': "Oslo Børs"},
           'OAX':  {'tickers': oax, 'long_name': "Oslo Axess"},
           'MERK': {'tickers': merk, 'long_name': "Merkur Market"}}
