#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import pickle
import argparse

# add relative python dir to pathx
script_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(script_dir, "../python"))

parser = argparse.ArgumentParser(description="Download market data")
parser.add_argument("--all", action="store_true", help="Download from all markets")
parser.add_argument("--oslobors", action="store_true", help="Download from Oslo Børs")
parser.add_argument("--nasdaqomx", action="store_true", help="Download from NasdaqOMX")
args = parser.parse_args()

def download_oslobors():
    from markets import OsloBors

    print("Downloading from Oslo Børs")
    oslobors = OsloBors()
    oslobors.download()

    print("Creating OsloBors object")
    oslobors = OsloBors()

    print("Loading the data into the OsloBors object")
    oslobors.load()

    print("Pickling the OsloBors object")
    oslobors.pickle()

def download_nasdaqomx():
    from markets import NasdaqOmx

    print("Downloading from Nasdaq OMX")
    nasdaqomx = NasdaqOmx()
    nasdaqomx.download()

    print("Loading the data into the NasdaqOmx object")
    nasdaqomx.load()

    print("Pickling the NasdaqOmx object")
    nasdaqomx.pickle()
    
if args.all or args.oslobors:
    download_oslobors()
    
if args.all or args.nasdaqomx:
    download_nasdaqomx()


