#!/usr/bin/env python3

import os
import sys

# add relative python dir to pathx
script_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(script_dir, "../python"))

from markets import OsloBors

oslobors = OsloBors()
oslobors.load()
