# -*- coding: utf-8 -*-

# Tickers on Oslo Børs
_market_ose = [("ASC", "ABG Sundal Collier Holding"),
               ("AFG", "AF Gruppen"),
               ("AKA", "Akastor"),
               ("AKER", "Aker"),
               ("AKERBP", "Aker BP"),
               ("AKSO", "Aker Solutions"),
               ("AKVA", "AKVA Group"),
               ("AMSC", "American Shipping Company"),
               ("APP", "Apptix"),
               ("AQUA", "Aqualis"),
               ("ARCHER", "Archer"),
               ("ARCUS", "Arcus"),
               ("AFK", "Arendals Fossekompani 2"),
               ("ASETEK", "Asetek"),
               ("ATEA", "Atea"),
               ("ATLA", "NOK Atlantic Petroleum"),
               ("AURG", "Aurskog Sparebank"),
               ("AUSS", "Austevoll Seafood"),
               ("AVANCE", "Avance Gas Holding"),
               ("AVM", "Avocet Mining"),
               ("AXA", "Axactor"),
               ("B2H", "B2Holding"),
               ("BAKKA", "Bakkafrost"),
               ("BEL", "Belships"),
               ("BERGEN", "Bergen Group"),
               ("BGBIO", "BerGenBio"),
               ("BIOTEC", "Biotec Pharmacon"),
               ("BON", "Bonheur"),
               ("BOR", "Borgestad"),
               ("BRG", "Borregaard"),
               ("BOUVET", "Bouvet"),
               ("BWLPG", "BW LPG"),
               ("BWO", "BW Offshore Limited"),
               ("BMA", "Byggma"),
               ("COV", "ContextVision"),
               ("CXENSE", "Cxense"),
               ("DAT", "Data Respons"),
               ("DESSC", "Deep Sea Supply"),
               ("DNB", "DNB"),
               ("DNO", "DNO"),
               ("DOF", "DOF"),
               ("EIOF", "Eidesvik Offshore"),
               ("EKO", "Ekornes"),
               ("EMGS", "Electromagnetic Geoservices"),
               ("EMAS", "EMAS Offshore"),
               ("ENTRA", "Entra"),
               ("EPR", "Europris"),
               ("FAR", "Farstad Shipping"),
               ("FOE", "Fred. Olsen Energy"),
               ("FRO", "Frontline"),
               ("FUNCOM", "Funcom"),
               ("GIG", "Gaming Innovation Group"),
               ("RISH", "GC Rieber Shipping"),
               ("GJF", "Gjensidige Forsikring"),
               ("GOGL", "Golden Ocean Group"),
               ("GOD", "Goodtech"),
               ("GSF", "Grieg Seafood"),
               ("GYL", "Gyldendal"),
               ("HNA", "Hafslund ser. A"),
               ("HNB", "Hafslund ser. B"),
               ("HAVI", "Havila Shipping"),
               ("HYARD", "Havyard Group"),
               ("HELG", "Helgeland Sparebank"),
               ("HEX", "Hexagon Composites"),
               ("HIDDN", "Hiddn Solutions"),
               ("HLNG", "Höegh LNG Holdings"),
               ("HSPG", "Høland og Setskog Sparebank"),
               ("IMSK", "I.M. Skaugen"),
               ("IDEX", "IDEX"),
               ("INC", "Incus Investor"),
               ("ISSG", "Indre Sogn Sparebank"),
               ("INSR", "Insr Insurance Group"),
               ("IOX", "InterOil Exploration and Production"),
               ("ITX", "Intex Resources"),
               ("ITE", "Itera"),
               ("JIN", "Jinhui Shipping and Transportation"),
               ("JAEREN", "Jæren Sparebank"),
               ("KID", "Kid"),
               ("KIT", "Kitron"),
               ("KOA", "Kongsberg Automotive"),
               ("KOG", "Kongsberg Gruppen"),
               ("KVAER", "Kværner"),
               ("LSG", "Lerøy Seafood Group"),
               ("LINK", "Link Mobility Group"),
               ("MHG", "Marine Harvest"),
               ("MEDI", "Medistim"),
               ("MELG", "Melhus Sparebank"),
               ("MULTI", "Multiconsult"),
               ("NAPA", "Napatech"),
               ("NAVA", "Navamedic"),
               ("NEL", "NEL"),
               ("NEXT", "NEXT Biometrics Group"),
               ("NGT", "NextGenTel Holding"),
               ("NANO", "Nordic Nanovector"),
               ("NOD", "Nordic Semiconductor"),
               ("NHY", "Norsk Hydro"),
               ("NSG", "Norske Skogindustrier"),
               ("NRS", "Norway Royal Salmon"),
               ("NAS", "Norwegian Air Shuttle"),
               ("NOR", "Norwegian Energy Company"),
               ("NOFI", "Norwegian Finans Holding"),
               ("NPRO", "Norwegian Property"),
               ("NRC", "NRC Group"),
               ("NTS", "NTS"),
               ("OCY", "Ocean Yield"),
               ("OTS", "Oceanteam"),
               ("ODL", "Odfjell Drilling"),
               ("ODF", "Odfjell ser. A"),
               ("ODFB", "Odfjell ser. B"),
               ("OLT", "Olav Thon Eiendomsselskap"),
               ("OPERA", "Opera Software"),
               ("ORK", "Orkla"),
               ("PEN", "Panoro Energy"),
               ("PARB", "Pareto Bank"),
               ("PGS", "Petroleum Geo-Services"),
               ("PDR", "Petrolia"),
               ("PHO", "Photocure"),
               ("PLCS", "Polarcus"),
               ("POL", "Polaris Media"),
               ("PRS", "Prosafe"),
               ("PROTCT", "Protector Forsikring"),
               ("QFR", "Q-Free"),
               ("QEC", "Questerre Energy Corporation"),
               ("RAKP", "RAK Petroleum"),
               ("REACH", "Reach Subsea"),
               ("REC", "REC Silicon"),
               ("RENO", "RenoNorden"),
               ("SALM", "SalMar"),
               ("SADG", "Sandnes Sparebank"),
               ("SAS", "NOK SAS AB"),
               ("SSO", "Scatec Solar"),
               ("SCHA", "Schibsted ser. A"),
               ("SCHB", "Schibsted ser. B"),
               ("SBX", "SeaBird Exploration"),
               ("SDRL", "Seadrill"),
               ("SBO", "Selvaag Bolig"),
               ("SEVDR", "Sevan Drilling"),
               ("SEVAN", "Sevan Marine"),
               ("SIOFF", "Siem Offshore"),
               ("SKBN", "Skandiabanken"),
               ("SKI", "Skiens Aktiemølle"),
               ("SKUE", "Skue Sparebank"),
               ("SOLON", "Solon Eiendom"),
               ("SOFF", "Solstad Offshore ser. A"),
               ("SOFFB", "Solstad Offshore ser. B"),
               ("SOLV", "Solvang"),
               ("SONG", "Songa Offshore"),
               ("SBVG", "SpareBank 1 BV"),
               ("NONG", "SpareBank 1 Nord-Norge"),
               ("RING", "SpareBank 1 Ringerike Hadeland"),
               ("MING", "SpareBank 1 SMN"),
               ("SRBANK", "SpareBank 1 SR-Bank"),
               ("SOAG", "SpareBank 1 Østfold Akershus"),
               ("MORG", "Sparebanken Møre"),
               ("SOR", "Sparebanken Sør"),
               ("SVEG", "Sparebanken Vest"),
               ("SPOG", "Sparebanken Øst"),
               ("SPU", "Spectrum"),
               ("STL", "Statoil"),
               ("SNI", "Stolt-Nielsen"),
               ("STB", "Storebrand"),
               ("STORM", "Storm Real Estate"),
               ("STRONG", "StrongPoint"),
               ("SUBC", "Subsea 7"),
               ("TIL", "Tanker Investments"),
               ("TRVX", "Targovax"),
               ("TEAM", "Team Tankers International"),
               ("TECH", "Techstep"),
               ("TEL", "Telenor"),
               ("TGS", "TGS-NOPEC Geophysical Company"),
               ("SSC", "The Scottish Salmon Company"),
               ("THIN", "Thin Film Electronics"),
               ("TOM", "Tomra Systems"),
               ("TOTG", "Totens Sparebank"),
               ("TRE", "Treasure"),
               ("TTS", "TTS Group"),
               ("VEI", "Veidekke"),
               ("VVL", "Voss Veksel- og Landmandsbank"),
               ("WWL", "Wallenius Wilhelmsen Logistics"),
               ("WEIFA", "Weifa"),
               ("WRL", "Wentworth Resources"),
               ("WWI", "Wilh. Wilhelmsen Holding ser. A"),
               ("WWIB", "Wilh. Wilhelmsen Holding ser. B"),
               ("WILS", "Wilson"),
               ("XXL", "XXL"),
               ("YAR", "Yara International"),
               ("ZAL", "Zalaris"),]

# Tickers on Oslo Axess
_market_oax = [("AEGA", "Aega"),
               ("APCL", "African Petroleum Corporation"),
               ("ABT", "Aqua Bio Technology"),
               ("AWDR", "Awilco Drilling"),
               ("ALNG", "Awilco LNG"),
               ("BXPL", "Badger Explorer"),
               ("EAM", "EAM Solar"),
               ("FLNG", "FLEX LNG"),
               ("HBC", "Hofseth BioCare"),
               ("HUGO", "Hugo Games"),
               ("MSEIS", "Magseis"),
               ("MCG", "MultiClient Geophysical"),
               ("NATTO", "NattoPharma"),
               ("NOM", "Nordic Mining"),
               ("NORTH", "North Energy"),
               ("PCIB", "PCI Biotech Holding"),
               ("PHLY", "Philly Shipyard"),
               ("PPG", "PREF Pioneer Property Group"),
               ("ROM", "RomReal"),
               ("SDSD", "S.D. Standard Drilling"),
               ("SAGA", "Saga Tankers"),
               ("SSHIP", "Scanship Holding"),
               ("UMS", "Unified Messaging Systems"),
               ("VISTIN", "Vistin Pharma"),]

# Tickers Merkur Market
_market_merk = [("AASB-ME", "Aasen Sparebank"),
                ("ATLU-ME", "Atlantic Lumpus"),
                ("BSP-ME", "Black Sea Property"),
                ("EPIC-ME", "Epic Gas"),
                ("GENT-ME", "Gentian Diagnostics"),
                ("INDUCT-ME", "Induct"),
                ("KOLKAP-ME", "Kolibri Kapital"),
                ("MONO-ME", "Monobank"),
                ("OXXY-ME", "Oxxy Group"),
                ("SIAF-ME", "Sino Agro Food"),
                ("SBULK-ME", "Songa Bulk"),
                ("WRE-ME", "WR Entertainment"),]

_sector_egenkapitalsbevis = [("AASB-ME", "Aasen Sparebank"),
                             ("AURG", "Aurskog Sparebank"),
                             ("HELG", "Helgeland Sparebank"),
                             ("HSPG", "Høland og Setskog Sparebank"),
                             ("ISSG", "Indre Sogn Sparebank"),
                             ("JAEREN", "Jæren Sparebank"),
                             ("MELG", "Melhus Sparebank"),
                             ("SADG", "Sandnes Sparebank"),
                             ("SKUE", "Skue Sparebank"),
                             ("SBVG", "SpareBank 1 BV"),
                             ("NONG", "SpareBank 1 Nord-Norge"),
                             ("RING", "SpareBank 1 Ringerike Hadeland"),
                             ("MING", "SpareBank 1 SMN"),
                             ("SOAG", "SpareBank 1 Østfold Akershus"),
                             ("MORG", "Sparebanken Møre"),
                             ("SOR", "Sparebanken Sør"),
                             ("SVEG", "Sparebanken Vest"),
                             ("SPOG", "Sparebanken Øst"),
                             ("TOTG", "Totens Sparebank"),]

_sector_energi = [("APCL", "African Petroleum Corporation"),
                  ("AKA", "Akastor"),
                  ("AKERBP", "Aker BP"),
                  ("AKSO", "Aker Solutions"),
                  ("AQUA", "Aqualis"),
                  ("ARCHER", "Archer"),
                  ("ATLA", "NOK Atlantic Petroleum"),
                  ("AVANCE", "Avance Gas Holding"),
                  ("AWDR", "Awilco Drilling"),
                  ("ALNG", "Awilco LNG"),
                  ("BXPL", "Badger Explorer"),
                  ("BERGEN", "Bergen Group"),
                  ("BON", "Bonheur"),
                  ("BWLPG", "BW LPG"),
                  ("BWO", "BW Offshore Limited"),
                  ("DESSC", "Deep Sea Supply"),
                  ("DNO", "DNO"),
                  ("DOF", "DOF"),
                  ("EIOF", "Eidesvik Offshore"),
                  ("EMGS", "Electromagnetic Geoservices"),
                  ("EMAS", "EMAS Offshore"),
                  ("EPIC-ME", "Epic Gas"),
                  ("FAR", "Farstad Shipping"),
                  ("FLNG", "FLEX LNG"),
                  ("FOE", "Fred. Olsen Energy"),
                  ("FRO", "Frontline"),
                  ("HAVI", "Havila Shipping"),
                  ("HLNG", "Höegh LNG Holdings"),
                  ("IMSK", "I.M. Skaugen"),
                  ("IOX", "InterOil Exploration and Production"),
                  ("KVAER", "Kværner"),
                  ("MSEIS", "Magseis"),
                  ("MCG", "MultiClient Geophysical"),
                  ("NORTH", "North Energy"),
                  ("NOR", "Norwegian Energy Company"),
                  ("OCY", "Ocean Yield"),
                  ("OTS", "Oceanteam"),
                  ("ODL", "Odfjell Drilling"),
                  ("PEN", "Panoro Energy"),
                  ("PGS", "Petroleum Geo-Services"),
                  ("PDR", "Petrolia"),
                  ("PLCS", "Polarcus"),
                  ("PRS", "Prosafe"),
                  ("QEC", "Questerre Energy Corporation"),
                  ("RAKP", "RAK Petroleum"),
                  ("REACH", "Reach Subsea"),
                  ("SDSD", "S.D. Standard Drilling"),
                  ("SAGA", "Saga Tankers"),
                  ("SBX", "SeaBird Exploration"),
                  ("SDRL", "Seadrill"),
                  ("SEVDR", "Sevan Drilling"),
                  ("SEVAN", "Sevan Marine"),
                  ("SIOFF", "Siem Offshore"),
                  ("SOFF", "Solstad Offshore ser. A"),
                  ("SOFFB", "Solstad Offshore ser. B"),
                  ("SONG", "Songa Offshore"),
                  ("SPU", "Spectrum"),
                  ("STL", "Statoil"),
                  ("SUBC", "Subsea 7"),
                  ("TIL", "Tanker Investments"),
                  ("TGS", "TGS-NOPEC Geophysical Company"),
                  ("WRL", "Wentworth Resources"),]

_sector_materialer = [("ABT", "Aqua Bio Technology"),
                      ("AVM", "Avocet Mining"),
                      ("BOR", "Borgestad"),
                      ("BRG", "Borregaard"),
                      ("INC", "Incus Investor"),
                      ("ITX", "Intex Resources"),
                      ("NOM", "Nordic Mining"),
                      ("NHY", "Norsk Hydro"),
                      ("NSG", "Norske Skogindustrier"),
                      ("YAR", "Yara International"),]

_sector_industri = [("AFG", "AF Gruppen"),
                    ("AKVA", "AKVA Group"),
                    ("AMSC", "American Shipping Company"),
                    ("BEL", "Belships"),
                    ("BMA", "Byggma"),
                    ("RISH", "GC Rieber Shipping"),
                    ("GOGL", "Golden Ocean Group"),
                    ("GOD", "Goodtech"),
                    ("HYARD", "Havyard Group"),
                    ("HEX", "Hexagon Composites"),
                    ("JIN", "Jinhui Shipping and Transportation"),
                    ("KOG", "Kongsberg Gruppen"),
                    ("MULTI", "Multiconsult"),
                    ("NEL", "NEL"),
                    ("NAS", "Norwegian Air Shuttle"),
                    ("NRC", "NRC Group"),
                    ("NTS", "NTS"),
                    ("ODF", "Odfjell ser. A"),
                    ("ODFB", "Odfjell ser. B"),
                    ("PHLY", "Philly Shipyard"),
                    ("RENO", "RenoNorden"),
                    ("SAS", "NOK SAS AB"),
                    ("SSHIP", "Scanship Holding"),
                    ("SOLV", "Solvang"),
                    ("SBULK-ME", "Songa Bulk"),
                    ("SNI", "Stolt-Nielsen"),
                    ("TEAM", "Team Tankers International"),
                    ("TOM", "Tomra Systems"),
                    ("TRE", "Treasure"),
                    ("TTS", "TTS Group"),
                    ("VEI", "Veidekke"),
                    ("WWL", "Wallenius Wilhelmsen Logistics"),
                    ("WWI", "Wilh. Wilhelmsen Holding ser. A"),
                    ("WWIB", "Wilh. Wilhelmsen Holding ser. B"),
                    ("WILS", "Wilson"),
                    ("ZAL", "Zalaris"),]

_sector_forbuksvarer = [("BSP-ME", "Black Sea Property"),
                        ("EKO", "Ekornes"),
                        ("EPR", "Europris"),
                        ("GYL", "Gyldendal"),
                        ("KID", "Kid"),
                        ("KOA", "Kongsberg Automotive"),
                        ("POL", "Polaris Media"),
                        ("SCHA", "Schibsted ser. A"),
                        ("SCHB", "Schibsted ser. B"),
                        ("WRE-ME", "WR Entertainment"),
                        ("XXL", "XXL"),]

_sector_konsumvarer = [("ARCUS", "Arcus"),
                       ("ATLU-ME", "Atlantic Lumpus"),
                       ("AUSS", "Austevoll Seafood"),
                       ("BAKKA", "Bakkafrost"),
                       ("GSF", "Grieg Seafood"),
                       ("LSG", "Lerøy Seafood Group"),
                       ("MHG", "Marine Harvest"),
                       ("NATTO", "NattoPharma"),
                       ("NRS", "Norway Royal Salmon"),
                       ("ORK", "Orkla"),
                       ("SALM", "SalMar"),
                       ("SIAF-ME", "Sino Agro Food"),
                       ("SSC", "The Scottish Salmon Company"),]

_sector_helsevern = [("BGBIO", "BerGenBio"),
                     ("BIOTEC", "Biotec Pharmacon"),
                     ("COV", "ContextVision"),
                     ("GENT-ME", "Gentian Diagnostics"),
                     ("HBC", "Hofseth BioCare"),
                     ("MEDI", "Medistim"),
                     ("NAVA", "Navamedic"),
                     ("NANO", "Nordic Nanovector"),
                     ("PCIB", "PCI Biotech Holding"),
                     ("PHO", "Photocure"),
                     ("TRVX", "Targovax"),
                     ("VISTIN", "Vistin Pharma"),
                     ("WEIFA", "Weifa"),]

_sector_finans = [("ASC", "ABG Sundal Collier Holding"),
                  ("AKER", "Aker"),
                  ("AXA", "Axactor"),
                  ("B2H", "B2Holding"),
                  ("DNB", "DNB"),
                  ("GJF", "Gjensidige Forsikring"),
                  ("INSR", "Insr Insurance Group"),
                  ("KOLKAP-ME", "Kolibri Kapital"),
                  ("MONO-ME", "Monobank"),
                  ("NOFI", "Norwegian Finans Holding"),
                  ("PARB", "Pareto Bank"),
                  ("PROTCT", "Protector Forsikring"),
                  ("SKBN", "Skandiabanken"),
                  ("SKI", "Skiens Aktiemølle"),
                  ("SRBANK", "SpareBank 1 SR-Bank"),
                  ("STB", "Storebrand"),
                  ("VVL", "Voss Veksel- og Landmandsbank"),]

_sector_it = [("APP", "Apptix"),
              ("ASETEK", "Asetek"),
              ("ATEA", "Atea"),
              ("BOUVET", "Bouvet"),
              ("CXENSE", "Cxense"),
              ("DAT", "Data Respons"),
              ("FUNCOM", "Funcom"),
              ("GIG", "Gaming Innovation Group"),
              ("HIDDN", "Hiddn Solutions"),
              ("HUGO", "Hugo Games"),
              ("IDEX", "IDEX"),
              ("INDUCT-ME", "Induct"),
              ("ITE", "Itera"),
              ("KIT", "Kitron"),
              ("LINK", "Link Mobility Group"),
              ("NAPA", "Napatech"),
              ("NEXT", "NEXT Biometrics Group"),
              ("NOD", "Nordic Semiconductor"),
              ("OPERA", "Opera Software"),
              ("OXXY-ME", "Oxxy Group"),
              ("QFR", "Q-Free"),
              ("REC", "REC Silicon"),
              ("STRONG", "StrongPoint"),
              ("TECH", "Techstep"),
              ("THIN", "Thin Film Electronics"),
              ("UMS", "Unified Messaging Systems"),]

_sector_telekom = [("NGT", "NextGenTel Holding"),
                   ("TEL", "Telenor"),]

_sector_forsyning = [("AEGA", "Aega"),
                     ("AFK", "Arendals Fossekompani 2"),
                     ("EAM", "EAM Solar"),
                     ("HNA", "Hafslund ser. A"),
                     ("HNB", "Hafslund ser. B"),
                     ("SSO", "Scatec Solar"),]

_sector_eiendom = [("ENTRA", "Entra"),
                   ("NPRO", "Norwegian Property"),
                   ("OLT", "Olav Thon Eiendomsselskap"),
                   ("PPG", "PREF Pioneer Property Group"),
                   ("ROM", "RomReal"),
                   ("SBO", "Selvaag Bolig"),
                   ("SOLON", "Solon Eiendom"),
                   ("STORM", "Storm Real Estate"),]

_segment_obx = [("AKERBP", "Aker BP"),
                ("AKSO", "Aker Solutions"),
                ("BAKKA", "Bakkafrost"),
                ("BWLPG", "BW LPG"),
                ("DNB", "DNB"),
                ("DNO", "DNO"),
                ("FRO", "Frontline"),
                ("GJF", "Gjensidige Forsikring"),
                ("GSF", "Grieg Seafood"),
                ("LSG", "Lerøy Seafood Group"),
                ("MHG", "Marine Harvest"),
                ("NHY", "Norsk Hydro"),
                ("NAS", "Norwegian Air Shuttle"),
                ("ORK", "Orkla"),
                ("PGS", "Petroleum Geo-Services"),
                ("REC", "REC Silicon"),
                ("SALM", "SalMar"),
                ("SCHA", "Schibsted ser. A"),
                ("SDRL", "Seadrill"),
                ("STL", "Statoil"),
                ("STB", "Storebrand"),
                ("SUBC", "Subsea 7"),
                ("TEL", "Telenor"),
                ("TGS", "TGS-NOPEC Geophysical Company"),
                ("YAR", "Yara International"),]

_segment_ob_match = [("ASC", "ABG Sundal Collier Holding"),
                     ("AFG", "AF Gruppen"),
                     ("AKA", "Akastor"),
                     ("AKER", "Aker"),
                     ("AKVA", "AKVA Group"),
                     ("AMSC", "American Shipping Company"),
                     ("AQUA", "Aqualis"),
                     ("ARCHER", "Archer"),
                     ("ARCUS", "Arcus"),
                     ("ASETEK", "Asetek"),
                     ("ATEA", "Atea"),
                     ("ATLA", "NOK Atlantic Petroleum"),
                     ("AUSS", "Austevoll Seafood"),
                     ("AVANCE", "Avance Gas Holding"),
                     ("AVM", "Avocet Mining"),
                     ("AXA", "Axactor"),
                     ("B2H", "B2Holding"),
                     ("BEL", "Belships"),
                     ("BERGEN", "Bergen Group"),
                     ("BIOTEC", "Biotec Pharmacon"),
                     ("BON", "Bonheur"),
                     ("BOR", "Borgestad"),
                     ("BRG", "Borregaard"),
                     ("BWO", "BW Offshore Limited"),
                     ("COV", "ContextVision"),
                     ("DAT", "Data Respons"),
                     ("DESSC", "Deep Sea Supply"),
                     ("DOF", "DOF"),
                     ("EIOF", "Eidesvik Offshore"),
                     ("EKO", "Ekornes"),
                     ("EMGS", "Electromagnetic Geoservices"),
                     ("ENTRA", "Entra"),
                     ("EPR", "Europris"),
                     ("FAR", "Farstad Shipping"),
                     ("FOE", "Fred. Olsen Energy"),
                     ("FUNCOM", "Funcom"),
                     ("GIG", "Gaming Innovation Group"),
                     ("GOGL", "Golden Ocean Group"),
                     ("GOD", "Goodtech"),
                     ("HNA", "Hafslund ser. A"),
                     ("HNB", "Hafslund ser. B"),
                     ("HAVI", "Havila Shipping"),
                     ("HYARD", "Havyard Group"),
                     ("HEX", "Hexagon Composites"),
                     ("HIDDN", "Hiddn Solutions"),
                     ("HLNG", "Höegh LNG Holdings"),
                     ("IDEX", "IDEX"),
                     ("INC", "Incus Investor"),
                     ("INSR", "Insr Insurance Group"),
                     ("IOX", "InterOil Exploration and Production"),
                     ("ITX", "Intex Resources"),
                     ("JIN", "Jinhui Shipping and Transportation"),
                     ("KID", "Kid"),
                     ("KIT", "Kitron"),
                     ("KOA", "Kongsberg Automotive"),
                     ("KOG", "Kongsberg Gruppen"),
                     ("KVAER", "Kværner"),
                     ("LINK", "Link Mobility Group"),
                     ("MEDI", "Medistim"),
                     ("MULTI", "Multiconsult"),
                     ("NAPA", "Napatech"),
                     ("NAVA", "Navamedic"),
                     ("NEL", "NEL"),
                     ("NEXT", "NEXT Biometrics Group"),
                     ("NGT", "NextGenTel Holding"),
                     ("NANO", "Nordic Nanovector"),
                     ("NOD", "Nordic Semiconductor"),
                     ("NSG", "Norske Skogindustrier"),
                     ("NRS", "Norway Royal Salmon"),
                     ("NOR", "Norwegian Energy Company"),
                     ("NOFI", "Norwegian Finans Holding"),
                     ("NPRO", "Norwegian Property"),
                     ("NRC", "NRC Group"),
                     ("OCY", "Ocean Yield"),
                     ("OTS", "Oceanteam"),
                     ("ODL", "Odfjell Drilling"),
                     ("ODF", "Odfjell ser. A"),
                     ("ODFB", "Odfjell ser. B"),
                     ("OLT", "Olav Thon Eiendomsselskap"),
                     ("OPERA", "Opera Software"),
                     ("PEN", "Panoro Energy"),
                     ("PARB", "Pareto Bank"),
                     ("PHO", "Photocure"),
                     ("PLCS", "Polarcus"),
                     ("PRS", "Prosafe"),
                     ("PROTCT", "Protector Forsikring"),
                     ("QFR", "Q-Free"),
                     ("QEC", "Questerre Energy Corporation"),
                     ("RENO", "RenoNorden"),
                     ("SAS", "NOK SAS AB"),
                     ("SSO", "Scatec Solar"),
                     ("SCHB", "Schibsted ser. B"),
                     ("SBX", "SeaBird Exploration"),
                     ("SBO", "Selvaag Bolig"),
                     ("SEVDR", "Sevan Drilling"),
                     ("SKBN", "Skandiabanken"),
                     ("SOLON", "Solon Eiendom"),
                     ("SOFF", "Solstad Offshore ser. A"),
                     ("SONG", "Songa Offshore"),
                     ("SRBANK", "SpareBank 1 SR-Bank"),
                     ("SPU", "Spectrum"),
                     ("SNI", "Stolt-Nielsen"),
                     ("STRONG", "StrongPoint"),
                     ("TIL", "Tanker Investments"),
                     ("TRVX", "Targovax"),
                     ("TECH", "Techstep"),
                     ("SSC", "The Scottish Salmon Company"),
                     ("THIN", "Thin Film Electronics"),
                     ("TOM", "Tomra Systems"),
                     ("TRE", "Treasure"),
                     ("TTS", "TTS Group"),
                     ("VEI", "Veidekke"),
                     ("VVL", "Voss Veksel- og Landmandsbank"),
                     ("WWL", "Wallenius Wilhelmsen Logistics"),
                     ("WEIFA", "Weifa"),
                     ("WRL", "Wentworth Resources"),
                     ("WWI", "Wilh. Wilhelmsen Holding ser. A"),
                     ("WWIB", "Wilh. Wilhelmsen Holding ser. B"),
                     ("XXL", "XXL"),
                     ("ZAL", "Zalaris"),]

_segment_ob_standard = [("APP", "Apptix"),
                        ("AFK", "Arendals Fossekompani 2"),
                        ("BGBIO", "BerGenBio"),
                        ("BOUVET", "Bouvet"),
                        ("BMA", "Byggma"),
                        ("CXENSE", "Cxense"),
                        ("EMAS", "EMAS Offshore"),
                        ("RISH", "GC Rieber Shipping"),
                        ("GYL", "Gyldendal"),
                        ("IMSK", "I.M. Skaugen"),
                        ("ITE", "Itera"),
                        ("NTS", "NTS"),
                        ("PDR", "Petrolia"),
                        ("POL", "Polaris Media"),
                        ("RAKP", "RAK Petroleum"),
                        ("REACH", "Reach Subsea"),
                        ("SEVAN", "Sevan Marine"),
                        ("SIOFF", "Siem Offshore"),
                        ("SKI", "Skiens Aktiemølle"),
                        ("SOFFB", "Solstad Offshore ser. B"),
                        ("SOLV", "Solvang"),
                        ("STORM", "Storm Real Estate"),
                        ("TEAM", "Team Tankers International"),
                        ("WILS", "Wilson"),]

_segment_ob_nye = [("BGBIO", "BerGenBio"),
                   ("SOFFB", "Solstad Offshore ser. B"),]

_markets = [('OSE', 'Oslo Børs all'),
            ('OAX', 'Oslo Axess'),
            ('MERK', 'Merkur Market')]

_indexes = [('OSEBX', 'Hovedindeksen'),
            ('OBX', 'OBX Total Return Index'),
            ('OSEAX', 'Oslo Børs All-share Index'),
            ('OAAX', 'Oslo Axess All-share index'),
            ('OSLENX', 'OSLO Energy Index'),
            ('OSLSHX', 'OSLO Shipping Index')]

